# Generated by Django 2.1.1 on 2018-09-11 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiftapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarday',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='calendarday',
            name='hoursofoperation',
        ),
        migrations.RemoveField(
            model_name='calendarday',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='employee',
        ),
    ]
